apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecosystem-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sbk0716 # 各自のリポジトリ
    targetRevision: main               # ブランチ名がmainの場合
    path: 'argocd/apps/'               # 検知対象のリソースが置かれたパス
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true